---
############   I used sleep to wait on terraform instead of using this task #############
# - name: Wait for SSH to come up
#   hosts: all
#   gather_facts: false
#   tasks:
#     - name: Wait for SSH to be available
#       wait_for:
#         port: 22
#         delay: 10
#         timeout: 300
#         search_regex: OpenSSH
#         host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
#       vars:
#         ansible_connection: local

- name: Install docker, docker-compose and start
  hosts: all
  become: true

  vars:
    docker_compose_version: "2.24.6"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        update_cache: true
        state: present

    - name: Create APT keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: "{{ ansible_facts['distribution_release'] }}"
        components:
          - stable
        architectures:
          - amd64
        signed_by: /etc/apt/keyrings/docker.asc
        state: present

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true
        state: present

    - name: Enable & start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true 

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version

    - debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"     

- name: Start docker containers
  hosts: all
  become: true
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker-compose.yaml to remote server
      copy:
        src: docker-compose-jma.yaml
        dest: /home/ubuntu/docker-compose-jma.yaml
        mode: '0644'

    - name: Docker login
      community.docker.docker_login: 
        registry_url: https://index.docker.io/v1/
        username: arman04
        password: "{{docker_password}}"
    

    - name: Start container from compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        files: 
          - docker-compose-jma.yaml
        state: present
        pull: always
        recreate: always
        environment:
          IMAGE_TAG: "{{ image_tag }}"